sudo: false

language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - "node"

before_script":
  - npm prune

script:
  - npm run test
  - npm run coverage-check

after_success:
  - npm run coverage-report
  - npm run semantic-release
